#!/usr/bin/env php
<?php

error_reporting(E_ERROR | E_PARSE);

if (php_sapi_name() !== 'cli') {
    echo "<h1>[*] Run only in CLI mode</h1>";
    exit;
}

use Src\Commands\BannerCommand;

require_once __DIR__ . '/vendor/autoload.php';


if (isset($argv[1]) and in_array($argv[1], ['--help', '-h'])) {
    BannerCommand::help();
    exit;
}

BannerCommand::init();


$addres = (string) readline("[*] Website address: ");
