#!/usr/bin/env php
<?php

error_reporting(E_ERROR | E_PARSE);

if (php_sapi_name() !== 'cli') {
    echo "<h1>[*] Run only in CLI mode</h1>";
    exit;
}

use Src\Commands\{BannerCommand, ScannerCommand};
use Src\Helpers\PortReader;
use Src\Tools\Printer;

require_once __DIR__ . '/vendor/autoload.php';

BannerCommand::init();

if (isset($argv[1]) and in_array($argv[1], ['--help', '-h'])) {
    BannerCommand::help();
    exit;
}

if (isset($argv[1]) and in_array($argv[1], ['-p'])) {
    $ports = PortReader::reader($argv[2]);
}

$address = isset($argv[1]) && $argv[1] !== '-p' ? $argv[1] : (string)  readline("> Website address: ");

$app = new ScannerCommand($address, $ports);

Printer::success("[*] Start port scanner on {$address}");

$app->scanner($address);
